### ISSUE TITLE
unneeded 'self' in callInfoFromWSDL function

### ISSUE THREAD

**Issue by alexyr** [pycontribs/wstools#13]
in WSDLTools.py:

`def callInfoFromWSDL(self, port, name):`

must be

`def callInfoFromWSDL(port, name):`

**Comment by ssbarnea** [comment]
PR?

**Comment by alexyr** [comment]
Sorry, I don't understand your question. This argument is not used in function and brokes soappy interaction with wstools

**Comment by ssbarnea** [comment]
I was just asking for you to make a pull request with the patch (removal of self param).

I did not use wstools myself in many years but if someone is raising a PR I will still try to help them get the fix in.

**Comment by alexyr** [comment]
@ssbarnea done
