### ISSUE TITLE
The pbr package is required, but it is not installed

### ISSUE THREAD

**Issue by cdonati** [pycontribs/wstools#20]
After installing the latest package from PyPI (0.4.7), I'm not able to import the package. I also tried the latest commit on the develop branch.

```
>>> import wstools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wstools/__init__.py", line 6, in <module>
    from pbr.version import VersionInfo
ImportError: No module named pbr.version
```

It seems the \_\_init\_\_.py file requires pbr, but it is not passed to the install_requires argument of setuptools.setup.

I'm using Python 2.7.14 and pip 9.0.3 on Linux.

**Comment by ssbarnea** [comment]
@cdonati fixed via 0.4.8 release. Thanks for pointing it.
