### ISSUE TITLE
[0.4.8] setup.{cfg,py} missing install_requires=['six'] ?

### ISSUE THREAD

**Issue by hartwork** [pycontribs/wstools#24]
Hi!

I see use of six both in Python code as well as in `requirements.txt`. Is there a reason why `setup.{cfg,py}` does not mention six for a runtime dependency?

Thanks and best, Sebastian

**Comment by ssbarnea** [comment]
PRs are welcomed, I am no longer using the project so even a new maintainer would be more than welcomed.

**Comment by hartwork** [comment]
Hi Sorin, thanks for your reply!
My recent contact with wstools was [upgrading the packaging in Gentoo to 0.4.8](https://github.com/gentoo/gentoo/commit/f8540d198d53fdcab9f90dd632f122be30804286). Other than that I don't use wstools directly, at the moment. I can make that pull request happen though, give me a moment.
