### ISSUE TITLE
archive or remove unmaintained wstools upstreams

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/wstools#31]
This repository was the only maintained copy wstools and both https://github.com/WebReply/wstools and https://github.com/kiorky/wstools got zero maintenance.

The forked status of current repository makes maintenance hard because github defaults getting pull request to upstream, which are abandonware.

This can be fixed one of more of the several approaches:
* convince the two upstreams to archive their repositories, or even remove them if they want
* ask github support to remove fork status from this repository
* dirty hack removing this repository and creating a new one from scratch, something I would only consider as last resort if both previous approaches would not work.

**Comment by ssbarnea** [comment]
@WebReply @kiorky ^^ Maybe you can help with that.

**Comment by kiorky** [comment]
hi @ssbarnea ,
Yes i know, we created this repository as a hope for new contributors to find this place to contribute to maintainance (i do not maintain it activly) as the maintainers are from long date missing to action ;).

Taking over another one project is not something i personally like to do.

**Comment by ssbarnea** [comment]
@kiorky I can understand. I think that the only idea was to use "archive" option on your fork, which should be enough to indicate is not maintained.

**Comment by kiorky** [comment]
Ha ok, it's done
