### ISSUE TITLE
Missing "import logging" in WSDLTools.py?

### ISSUE THREAD

**Issue by alexyr** [pycontribs/wstools#9]
After updating today I started to get "NameError: global name 'logging' is not defined"
when using SOAPpy:
...
  File "C:\Python27\lib\site-packages\SOAPpy\WSDL.py", line 97, in **init**
    callinfo = wstools.WSDLTools.callInfoFromWSDL(port, operation.name)
  File "C:\Python27\lib\site-packages\wstools\WSDLTools.py", line 1607, in callInfoFromWSDL
    logger = logging.getLogger(**name**)
NameError: global name 'logging' is not defined

**Comment by kyleballing** [comment]
Seriously! How did this get released?

**Comment by jdpye** [comment]
Just found this one in the middle of a workshop. =( =(

**Comment by efloehr** [comment]
Is it possible to release 0.4.5 into the Python Package Index, as 0.4.4 is unusable due to this issue. So if you want a working wstools, you have to come here.

**Comment by ssbarnea** [comment]
Thanks for reminding me, just released it.
